blog/urls.py
from django.urls import path
from . import views
app_name = 'blog'

urlpatterns = [
    path('', views.archive_blog, name="archive_blog"),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name="post_detail"),
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('', views.order_create, name='checkout'),
    path('pay/<int:id>/', views.order_pay, name='pay'),
    path('pay/complete/', views.order_complete, name='complete'),
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from catalog.sitemaps import ProductSitemap
from blog.sitemaps import ArticleSitemap

sitemaps = {'products': ProductSitemap,
            'posts': ArticleSitemap
            }

urlpatterns = [
    path('cart/', include('cart.urls', namespace='cart')),
    path('checkout/', include('orders.urls', namespace='orders')),
    path('wishlist/', include('wishlist.urls', namespace='wishlist')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('info/', include('pages.urls', namespace='info')),
    path('contacts/', include('contacts.urls', namespace='contacts')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('uploads/', include('uploads.urls', namespace='uploads')),
    path('information-security/', include('textpages.urls', namespace='information-security')),
    path('it-services/', include('textpages2.urls', namespace='it-services')),
    path('producers/', include('brands.urls', namespace='brands')),
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/forms.py
from django import forms


class CartAddProductForm(forms.Form):
    quantity = forms.CharField(initial=1, widget=forms.NumberInput(attrs={
        'min': 1,
        'max': 99,
        'type': 'number',
        'class': 'quantity__input'
    }))
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_POST
from catalog.models import Product
from .cart import Cart
from .forms import CartAddProductForm
from django.urls import reverse
from django.http import JsonResponse
from shop.settings import TITLE_SUFFIX


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)

    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=int(cd['quantity']), update_quantity=cd['update'])
        if request.is_ajax:
            return JsonResponse({
                'status': 'ok',
                'cnt': len(cart)
            })
    if request.is_ajax:
        return JsonResponse({
            'status': 'bad',
            'cnt': len(cart)
        })
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    breadcrumbs = []
    title = f'Корзина{TITLE_SUFFIX}'
    breadcrumbs.append({
        'label': 'Корзина',
        'url': reverse('cart:cart_detail'),
        'type': 'text',

    })
    return render(request, 'cart/detail.html', {'cart': cart, 'breadcrumbs': breadcrumbs, 'title': title})

cart/templates/cart/cart-totals.html
{% load static %}

<div class="cart-form__totals cart-totals">
    <div class="cart-totals__label">
        <div class="thumb">
            <img src="{% static 'img/icon-cart-dark.png' %}" alt="корзина">
        </div>
        <h2 class="cart-totals__title">Итого</h2>
    </div>
    <div class="cart-totals__info">
        <p class="cart-totals__subtotal">
            <span>Итого:</span>
            <strong>₽ {{ cart.get_total_price | floatformat:"0" }}</strong>
        </p>
        <p class="cart-totals__delivery">
            <span>Доставка:</span>
            <strong>₽ 0,00</strong>
        </p>
    </div>
    <div class="cart-totals__to-checkout">
        <p class="cart-totals__total">
            <span>Всего:</span>
            <strong>₽ {{ cart.get_total_price | floatformat:"0" }}</strong>
        </p>
        {% if submit_text %}
            <button type="submit" class="btn_submit-cart">{% firstof submit_text 'Оформить заказ' %}</button>
        {% else %}
        <a href="{% url 'orders:checkout' %}" class="btn_submit-cart">
            {% firstof submit_text 'Оформить заказ' %}</a>
        {% endif %}
    </div>
</div>

cart/templates/cart/cart.html
{% load static %}
{% load thumbnail %}
{% load cart_tags %}

<ul class="cart-form__products cart-products">
    {% for product in cart  %}

        <li class="cart-products__item cart-product">
            <div class="cart-product__thumb">
                <a href="{{ product.get_absolute_url }}" class="thumb">
                    {% if product.images.first %}
                        <img src="{{ product.images.first.file | thumbnail_url:'medium' }}"
                             alt="{{ product.images.first.alt  }}"
                        loading="lazy">
                    {% endif %}
                </a>
            </div>

            <div class="cart-product__name" data-label="Товар">
                <h2 class="cart-product__title">
                    <a href="{{ product.get_absolute_url }}">
                        {{ product.name }}
                    </a>
                </h2>
                <p class="cart-product__sku">
                    <span>Артикул:</span>
                    <strong>{% firstof product.sku '#Н/Д' %}</strong>
                </p>
            </div>
            <div class="cart-product__info">
                <p class="cart-product__quantity" data-label="Количество">
                    <span>Количество: </span>
                    <strong>{% cart_quantity cart.cart product.pk %}</strong>
                </p>
                <p class="cart-product__price" data-label="Цена">
                    <span>Цена: </span>
                    <strong>{% cart_subtotal cart.cart product.pk %} руб.</strong>
                </p>
            </div>
            <div class="product-remove__wrapper">
                <a href="{% url 'cart:cart_remove' product.id %}" class="cart-product__remove"
                   aria-label="удалить товар из корзины"></a>
            </div>
        </li>
    {% endfor %}
</ul>

cart/templates/cart/detail.html
{% extends 'layout/base.html' %}
{% load static %}
{% load thumbnail %}

{% block title %}Корзина{% endblock %}

{% block breadcrumbs %}
{% include 'breadcrumbs.html' %}
{% endblock %}

{% block content %}
<section class="cart">
    <div class="container">
        <div class="section-header">
            <h1 class="section-header__title">Корзина</h1>
        </div>
        {% if cart %}
        <div class="cart-form">
            {% include 'cart/cart.html' %}
            {% include 'cart/cart-totals.html' %}
        </div>
        {% else %}
        <p>Ваша корзина пуста.</p>
        {% endif %}
    </div>
</section>
<!-- /.cart -->
{% endblock %}