blog/urls.py
from django.urls import path
from . import views
app_name = 'blog'

urlpatterns = [
    path('', views.archive_blog, name="archive_blog"),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name="post_detail"),
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from catalog.sitemaps import ProductSitemap
from blog.sitemaps import ArticleSitemap

sitemaps = {'products': ProductSitemap,
            'posts': ArticleSitemap
            }

urlpatterns = [
    path('cart/', include('cart.urls', namespace='cart')),
    path('checkout/', include('orders.urls', namespace='orders')),
    path('wishlist/', include('wishlist.urls', namespace='wishlist')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('info/', include('pages.urls', namespace='info')),
    path('contacts/', include('contacts.urls', namespace='contacts')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('uploads/', include('uploads.urls', namespace='uploads')),
    path('information-security/', include('textpages.urls', namespace='information-security')),
    path('it-services/', include('textpages2.urls', namespace='it-services')),
    path('producers/', include('brands.urls', namespace='brands')),
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

wishlist/urls.py
from django.urls import path
from . import views

app_name = 'wishlist'

urlpatterns = [
    path('', views.wishlist_detail, name='wishlist_detail'),
    path('add/<int:product_id>/', views.wishlist_add, name='wishlist_add'),
]

wishlist/models.py
from django.db import models

# Create your models here.

wishlist/views.py
from django.shortcuts import render, get_object_or_404
from catalog.models import Product
from django.http import JsonResponse
from .wishlist import Wishlist
from django.views.decorators.http import require_POST
from shop.settings import TITLE_SUFFIX


def wishlist_detail(request):
    breadcrumbs = []
    breadcrumbs.append({
        'label': 'Избранное',
        'url': '',
        'type': 'text'
    })
    title = f'Список избранного{TITLE_SUFFIX}'
    return render(request, 'wishlist/wishlist-page.html', {'breadcrumbs': breadcrumbs,
                                                           'title': title})


@require_POST
def wishlist_add(request, product_id):
    wishlist = Wishlist(request)
    product = get_object_or_404(Product, id=product_id)
    if request.POST.get('method') == 'add':
        if str(product_id) in wishlist.wishlist:
            return JsonResponse({
                'status': 'already added',
                'cnt': len(wishlist),
            })
        else:
            wishlist.add(product)
            return JsonResponse({
                'status': 'added',
                'cnt': len(wishlist)
            })
    else:
        wishlist.remove(product)
        return JsonResponse({
            'status': 'removed',
            'cnt': len(wishlist)
        })

wishlist/templates/wishlist/add-to-wishlist-form.html
{% load static %}
<form class="add-to-wishlist-form" action="{% url 'wishlist:wishlist_add' product.id %}" method="post">
    {% csrf_token %}
    {% if product.id|stringformat:"i" in wishlist.wishlist %}
    <input type="hidden" name="method" value="remove">
    {% else %}
    <input type="hidden" name="method" value="add">
    {% endif %}
    <button class="btn btn_add-to-wishlist{% if product.id|stringformat:'i' in wishlist.wishlist %} active{% endif %}" type="submit" aria-label="добавить или удалить из избранного">
        <img src="{% static 'img/icon-heart.png' %}" alt="сердце" loading="lazy">
    </button>
</form>

wishlist/templates/wishlist/wishlist-page.html
{% extends 'layout/base.html' %}

{% block title %}Избранное{% endblock %}

{% block content %}
<main class="catalog">
    <div class="container">
        <div class="section-header section-header_flex">
            <h1 class="section-header__title">Избранное</h1>
        </div>

        <div class="catalog-group_wishlist">
            <div class="catalog__products">
                {% if wishlist|length %}
                <ul class="wishlist-group">
                    {% for item in wishlist %}
                    {% include 'catalog/archive-product.html' with product=item %}
                    {% endfor %}
                </ul>
                {% else %}
                <p class="empty-wishlist">Ваш список избранного пуст.</p>
                {% endif %}
            </div>
        </div>
    </div>
</main>
{% endblock %}