blog/urls.py
from django.urls import path
from . import views
app_name = 'blog'

urlpatterns = [
    path('', views.archive_blog, name="archive_blog"),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name="post_detail"),
]

contacts/urls.py
from django.urls import path
from .views import page_detail, send_message
app_name = 'contacts'


urlpatterns = [
    path('', page_detail, name="page"),
    path('send_message', send_message, name="send_message")
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from catalog.sitemaps import ProductSitemap
from blog.sitemaps import ArticleSitemap

sitemaps = {'products': ProductSitemap,
            'posts': ArticleSitemap
            }

urlpatterns = [
    path('cart/', include('cart.urls', namespace='cart')),
    path('checkout/', include('orders.urls', namespace='orders')),
    path('wishlist/', include('wishlist.urls', namespace='wishlist')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('info/', include('pages.urls', namespace='info')),
    path('contacts/', include('contacts.urls', namespace='contacts')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('uploads/', include('uploads.urls', namespace='uploads')),
    path('information-security/', include('textpages.urls', namespace='information-security')),
    path('it-services/', include('textpages2.urls', namespace='it-services')),
    path('producers/', include('brands.urls', namespace='brands')),
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contacts/models.py
from django.db import models
from django.urls import reverse


class Contact(models.Model):
    phone_1 = models.CharField(max_length=20, verbose_name='телефон 1')
    email = models.EmailField(verbose_name='E-mail')
    address = models.TextField(verbose_name='Адрес')
    map = models.TextField(verbose_name='iframe карты')
    schedule = models.CharField(max_length=200, verbose_name='График работы')
    facebook = models.URLField()
    instagram = models.URLField()

    def __str__(self):
        return 'Контакты'

    def get_absolute_url(self):
        return reverse('contacts:page')

    class Meta:
        verbose_name = 'Контакт'
        verbose_name_plural = 'Контакты'

contacts/forms.py
from django import forms


class FeadbackForm(forms.Form):
    name = forms.CharField(label=False, widget=forms.TextInput(attrs={
        'placeholder': 'Ваше имя',
        'class': 'feadback-form__input'
    }))
    tel = forms.CharField(label=False, widget=forms.TextInput(attrs={
        'placeholder': 'Телефон',
        'type': 'tel',
        'class': 'feadback-form__input'
    }))

contacts/views.py
from django.shortcuts import render
from django.http import JsonResponse, Http404
from .models import Contact
import re
from .forms import FeadbackForm
from django.views.decorators.http import require_POST
from django.core.mail import EmailMessage
from shop.settings import SEND_MAIL_TO, TITLE_SUFFIX


def page_detail(request):
    page = Contact.objects.first()
    if not page:
        raise Http404
    phone_link = 'tel+' + re.sub(r'\D', '', page.phone_1)
    form = FeadbackForm()
    breadcrumbs = [{
        'label': 'Контакты',
        'url': '',
        'type': 'text'
    }]
    title = f'Контакты{TITLE_SUFFIX}'
    context = {
        'page': page,
        'phone_link': phone_link,
        'form': form,
        'breadcrumbs': breadcrumbs,
        'title': title
    }

    return render(request, 'contacts/page.html', context)


@require_POST
def send_message(request):
    form = FeadbackForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        name = cd['name']
        tel = cd['tel']
        message = f'Имя: {name} \nНомер телефона: {tel}'
        em = EmailMessage(subject='Новое сообщение с сайта',
                          body=message,
                          to=[SEND_MAIL_TO],
                          headers={'content-type': 'text/html'}
                          )
        try:
            em.send()
            return JsonResponse({'status': 'ok'})
        except:
            return JsonResponse({'status': 'bad'})

contacts/templates/contacts/page.html
{% extends 'layout/base.html' %}
{% load static %}

{% block title %}Контакты{% endblock %}

{% block breadcrumbs %}
{% include 'breadcrumbs.html' %}
{% endblock %}


{% block content %}
<section class="contacts">
    <div class="container">
        <div class="section-header">
            <h1 class="section-header__title">Контакты</h1>
        </div>
        <div class="contacts-row">
            <div class="contacts__info">

                <div class="contacts__group contacts-group">
                    <h3 class="contacts-group__title">
                        <div class="thumb">
                            <img src="{% static 'img/icon-phone.png' %}" alt="телефон">
                        </div>
                        <span>Телефоны</span>
                    </h3>
                    <a href="{{ phone_link }}" class="contacts-group__link">{{ page.phone_1 }}</a>
                    <p class="contacts-group__desc">(Бесплатный звонок по России)</p>
                </div>

                <div class="contacts__group contacts-group">
                    <h3 class="contacts-group__title">
                        <div class="thumb">
                            <img src="{% static 'img/icon-mail.png' %}" alt="почта">
                        </div>
                        <span>E-mail</span>
                    </h3>
                    <a href="malito:{{ page.email }}" class="contacts-group__link">{{ page.email }}</a>
                </div>

                <div class="contacts__group contacts-group">
                    <h3 class="contacts-group__title">
                        <div class="thumb">
                            <img src="{% static 'img/icon-marker.png' %}" alt="маркер">
                        </div>
                        <span>Пункт Самовывоза</span>
                    </h3>
                    <p class="contacts-group__link">{{ page.address }}</p>
                </div>

                <div class="contacts__group contacts-group">
                    <h3 class="contacts-group__title">
                        <div class="thumb">
                            <img src="{% static 'img/icon-schedule.png' %}" alt="график">
                        </div>
                        <span>Режим работы</span>
                    </h3>
                    <p class="contacts-group__link">{{ page.schedule }}</p>
                </div>
            </div>
            <!-- /.contacts-info -->

            <div class="contacts__map">
                {{ page.map | safe }}
            </div>
        </div>
    </div>
</section>
<!-- /.contacts -->

<section class="feadback">
    <div class="container">
        <div class="feadback-row">
            <div class="section-header">
                <h2 class="section-header__title">Задать вопрос</h2>
                <p class="section-header__subtitle">Вы можете задать любой интересующий вас вопрос по товару или работе магазина. Наши квалифицированные специалисты обязательно вам помогут.</p>
            </div>

            <form class="feadback-form" method="post" action="{% url 'contacts:send_message' %}">
                <h3 class="feadback-form__title">Форма связи</h3>
                {% csrf_token %}
                {{ form }}
                <button type="submit" class="feadback-form__submit btn_submit">Отправить</button>
            </form>
        </div>



    </div>
</section>
<!-- /.feadback -->
{% endblock %}