blog/urls.py
from django.urls import path
from . import views
app_name = 'blog'

urlpatterns = [
    path('', views.archive_blog, name="archive_blog"),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name="post_detail"),
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

catalog/urls.py
from . import views
from django.urls import path

app_name = 'catalog'

urlpatterns = [
    path('', views.index, name='home'),
    path('mailru-domain5W5yyJrtllzru9Pg.html/', views.mailru, name='mail_ru'),
    path('search/', views.search, name='search'),
    path('question/', views.question, name='question'),
    path('product/<slug:slug>/', views.product_detail, name='product_detail'),
    path('product/<slug:slug>/<str:params>/', views.product_detail_filtered, name='product_detail_filtered'),
    path('product-cat/<slug:slug>/', views.products_by_cat, name='products_by_cat'),
    path('product-cat/<slug:slug>/<str:params>/', views.products_by_attr, name='products_by_attribute')
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from catalog.sitemaps import ProductSitemap
from blog.sitemaps import ArticleSitemap

sitemaps = {'products': ProductSitemap,
            'posts': ArticleSitemap
            }

urlpatterns = [
    path('cart/', include('cart.urls', namespace='cart')),
    path('checkout/', include('orders.urls', namespace='orders')),
    path('wishlist/', include('wishlist.urls', namespace='wishlist')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('info/', include('pages.urls', namespace='info')),
    path('contacts/', include('contacts.urls', namespace='contacts')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('uploads/', include('uploads.urls', namespace='uploads')),
    path('information-security/', include('textpages.urls', namespace='information-security')),
    path('it-services/', include('textpages2.urls', namespace='it-services')),
    path('producers/', include('brands.urls', namespace='brands')),
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/forms.py
from django import forms


class SearchForm(forms.Form):
    query = forms.CharField(label=False, widget=forms.TextInput(attrs={'placeholder': 'Поиск'}))

catalog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import JsonResponse
from .models import Product, Category, Delivery, Tag
from .utils import get_filters, get_prices, get_filtered_products, get_min_price, get_variation_filters, \
    get_filtered_var_products
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import SearchForm
from django.contrib.postgres.search import TrigramSimilarity
from django.db.models import Q
from reviews.forms import ReviewForm
from random import shuffle
from blog.models import Article
from config.models import Config
from django.core.mail import EmailMessage
from shop.settings import SEND_MAIL_TO
from contacts.models import Contact
from shop.settings import TITLE_SUFFIX
from django.views.decorators.cache import cache_page


def mailru(request):
    return render(request, 'catalog/mailru.html', {})


def index(request):
    articles = Article.published.all()[:12]
    top_products = Product.simple.all().order_by('-sales')[:12]
    exclude_list = list(item.id for item in top_products)
    new_products = Product.simple.exclude(pk__in=exclude_list)[:12]
    new_products_r = list(new_products)
    shuffle(new_products_r)
    config = Config.objects.first()
    banner_product = False
    title = f'Главная{TITLE_SUFFIX}'
    try:
        banner_products = list(config.main_product.all())
        if banner_products:
            shuffle(banner_products)
            banner_product = banner_products[0]
    except:
        pass

    brands = False
    try:
        brands = config.brands.all()
    except:
        pass
    context = {
        'top_products': top_products,
        'articles': articles,
        'new_products': new_products_r,
        'banner_product': banner_product,
        'brands': brands,
        'title': title
    }
    return render(request, 'catalog/index.html', context)


# @cache_page(60 * 1440)
def product_detail(request, slug):
    delivery = Delivery.objects.first()
    product = get_object_or_404(Product, slug=slug)
    variations = product.variations.all().values('pk')
    tags = None
    min_price = None
    filters = None
    if variations.count() > 0:
        product_type = 'variable'
        tags = Tag.objects.filter(products__id__in=variations).distinct()
        min_price = get_min_price(variations)
        filters = get_variation_filters(product)
    else:
        product_type = 'simple'

    title = f'{product.name}{TITLE_SUFFIX}'
    review_form = ReviewForm(initial={'product': product,
                                      'rating': 5})
    if request.method == 'POST':
        review_form = ReviewForm(request.POST)
        if review_form.is_valid():
            review = review_form.save()
            if request.is_ajax:
                return render(request, 'reviews/review-detail.html', {'review': review})

    category = product.category
    parent_category = category.parent_category
    product_attributes = []
    breadcrumbs = []
    if parent_category:
        breadcrumbs.append({
            'label': parent_category.name,
            'url': parent_category.get_absolute_url,
            'type': 'link'
        })
    if category:
        breadcrumbs.append({
            'label': category.name,
            'url': category.get_absolute_url,
            'type': 'link'
        })

    breadcrumbs.append({
        'label': product.name,
        'url': product.get_absolute_url,
        'type': 'text'
    })

    for attribute in product.attributes.all():
        try:
            kit = attribute.kit_set.get(product=product)
            product_attributes.append({
                'name': attribute.name,
                'value': kit.value
            })
        except:
            pass
    similar_products = list(Product.simple.filter(category=category).exclude(id=product.id))
    shuffle(similar_products)
    accessories_cats = product.accessories.all()
    accessories = list(Product.simple.filter(category__in=accessories_cats))
    shuffle(accessories)
    context = {
        'product': product,
        'product_attributes': product_attributes,
        'breadcrumbs': breadcrumbs,
        'review_form': review_form,
        'similar_products': similar_products[:24],
        'accessories': accessories,
        'delivery': delivery,
        'title': title,
        'product_type': product_type,
        'variations': variations,
        'min_price': min_price,
        'tags': tags,
        'filters': filters
    }
    print(variations)
    return render(request, 'catalog/single.html', context)


def product_detail_filtered(request, slug, params):
    delivery = Delivery.objects.first()
    product = get_object_or_404(Product, slug=slug)
    var_products = product.variations.all()
    tags = None
    min_price = None
    filters = None
    if var_products.count() > 0:
        product_type = 'variable'

        min_price = get_min_price(var_products)
        filters = get_variation_filters(product)
        query_filters = []
        params_list = params.split(';')
        for p in params_list:
            p_list = p.split(':')
            key = p_list[0]
            vals = p_list[1].split('=')
            query_filters.append({
                'key': key,
                'values': vals
            })
        products = get_filtered_var_products(var_products, query_filters)
        products_for_filter = products.values('pk')
        var_list_products = list(p.id for p in products)
        tags = Tag.objects.filter(products__id__in=products_for_filter).distinct()
    else:
        product_type = 'simple'

    title = f'{product.name}{TITLE_SUFFIX}'
    review_form = ReviewForm(initial={'product': product,
                                      'rating': 5})
    if request.method == 'POST':
        review_form = ReviewForm(request.POST)
        if review_form.is_valid():
            review = review_form.save()
            if request.is_ajax:
                return render(request, 'reviews/review-detail.html', {'review': review})

    category = product.category
    parent_category = category.parent_category
    product_attributes = []
    breadcrumbs = []
    if parent_category:
        breadcrumbs.append({
            'label': parent_category.name,
            'url': parent_category.get_absolute_url,
            'type': 'link'
        })
    if category:
        breadcrumbs.append({
            'label': category.name,
            'url': category.get_absolute_url,
            'type': 'link'
        })

    breadcrumbs.append({
        'label': product.name,
        'url': product.get_absolute_url,
        'type': 'text'
    })

    for attribute in product.attributes.all():
        try:
            kit = attribute.kit_set.get(product=product)
            product_attributes.append({
                'name': attribute.name,
                'value': kit.value
            })
        except:
            pass
    similar_products = list(Product.simple.filter(category=category).exclude(id=product.id))
    shuffle(similar_products)
    accessories_cats = product.accessories.all()
    accessories = list(Product.simple.filter(category__in=accessories_cats))
    shuffle(accessories)
    context = {
        'product': product,
        'product_attributes': product_attributes,
        'breadcrumbs': breadcrumbs,
        'review_form': review_form,
        'similar_products': similar_products[:24],
        'accessories': accessories,
        'delivery': delivery,
        'title': title,
        'product_type': product_type,
        'min_price': min_price,
        'tags': tags,
        'filters': filters,
        'var_list_products': var_list_products,
        'filtered': 'yes'
    }
    return render(request, 'catalog/single.html', context)


@cache_page(60 * 1440)
def products_by_cat(request, slug):
    category = get_object_or_404(Category, slug=slug)
    title = f'{category.name}{TITLE_SUFFIX}'
    children_categories = category.category_set.all()
    q = Q(category=category)
    for children_category in children_categories:
        q |= Q(category=children_category)

    products_list = Product.simple.filter(q).order_by('-sales')
    form = SearchForm()
    query = None
    if 'query' in request.GET:
        prices = get_prices(products_list, request)
        filters = get_filters(request, category, children_categories)
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            products_list = products_list.annotate(similarity=TrigramSimilarity('name', query))\
                .filter(similarity__gt=0.045).order_by('-similarity')

            breadcrumbs = []
            parent_category = category.parent_category
            if parent_category:
                breadcrumbs.append({
                    'label': parent_category.name,
                    'url': parent_category.get_absolute_url,
                    'type': 'link'
                })
            breadcrumbs.append({
                'label': category.name,
                'url': category.get_absolute_url,
                'type': 'text'
            })
            title = f'Результаты поиска: "{query}"{TITLE_SUFFIX}'
            context = {
                'category': category,
                'products': products_list,
                'prices': prices,
                'filters': filters,
                'search_form': form,
                'query_string': query,
                'breadcrumbs': breadcrumbs,
                'slug': slug,
                'title': title
            }

            return render(request, 'catalog/catalog.html', context)

    if request.method == 'GET':
        filters = get_filters(request, category, children_categories)
        prices = get_prices(products_list, request)

        paginator = Paginator(products_list, 12)
        page = request.GET.get('page')
        try:
            products = paginator.page(page)
        except PageNotAnInteger:

catalog/templates/catalog/archive-product.html
{% load static %}
{% load thumbnail %}
<li class="archive-product">
    <div class="archive-product__inner">
        <a href="{{ product.get_absolute_url }}" class="thumb">
            {% if product.images.first %}
                {% if product.images.first.file %}
                <img src="{{ product.images.first.file | thumbnail_url:'medium' }}" alt="{{ product.images.first.alt  }}"
                loading="lazy">
                {% elif product.images.first.image_url %}
                <img src="{{ product.images.first.image_url }}" alt="{{ product.images.first.alt  }}"
                loading="lazy">
                {% endif %}
            {% endif %}
        </a>
        <h3 class="archive-product__title">
            <a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
        </h3>
        {% if product.excerpt %}
        <p class="archive-product__desc">
            {{ product.excerpt }}
        </p>
        {% endif %}
        <p class="archive-product__price">
            <span class="current">
                {% if product.price == 1.00 %}
                    <p>Цена по запросу</p>
                {% else %}
                    {% if product.price_sale %}
                    <del>
                        {{ product.price | floatformat:"0" }} руб.
                    </del>
                    &nbsp;
                    <ins>
                        {{ product.price_sale | floatformat:"0" }} руб.
                    </ins>
                    {% else %}
                        <span>
                            {{ product.price | floatformat:"0" }} руб.
                        </span>
                    {% endif %}
                {% endif %}

            </span>
        </p>
        <div class="archive-product__controls">
            {% include 'wishlist/add-to-wishlist-form.html' %}
            <form class="add-to-cart-form add-to-cart-form_acrhive" action="{% url 'cart:cart_add' product.id %}" method="post">
                {% csrf_token %}
                {{ cart_product_form.as_p }}
                <button type="submit" class="btn btn__add-to-cart">В корзину</button>
                <a class="go-to-cart-link" href="{% url 'cart:cart_detail' %}" aria-label="перейти в корзину"></a>
            </form>
        </div>
    </div>
</li>

catalog/templates/catalog/catalog.html
{% extends 'layout/base.html' %}
{% load static %}

{% block title %} {{ category.name }} {% endblock %}

{% block breadcrumbs %}
{% include 'breadcrumbs.html' %}
{% endblock %}

{% block content %}
<main class="catalog">
    <div class="container">
        <h1 class="section-header__title">
            {% firstof extra_header category.name %}
        </h1>
        <div class="section-header section-header_flex">

            <div class="headers-controls__ordering">
                <label for="product-order">Сортировать:</label>
                <div class="select-wrapper">
                    <select name="product-order" id="product-order">
                        <option value="rating">По рейтингу</option>
                        <option value="new">По новизне</option>
                        <option value="price_asc">От дешевых к дорогим</option>
                        <option value="price_desc">От дорогих к дешевым</option>
                        <option value="discount">Сначала товары со скидкой</option>
                    </select>
                </div>
            </div>
            <div class="section-header__controls header-controls_s">
                <button type="button" data-class="list" class="header-controls__btn list" aria-label="в виде списка">
                    <span></span><span></span><span></span><span></span><span></span><span></span>
                </button>
                <button type="button" data-class="grid" class="header-controls__btn grid active" aria-label="в виде плитки">
                    <span></span><span></span><span></span><span></span><span></span><span></span><span></span><span></span><span></span>
                </button>
            </div>
            <div class="header-filters__btn-wrapper">
                <button class="header-filters__btn" type="button" aria-label="показать фильтры"></button>
            </div>
        </div>

        <div class="catalog-group">
            {% include 'catalog/sidebar.html' %}
            <div class="catalog__products">
                <div class="notice">
                    {% if query_string %}
                    <h2 class="catalog-results">Результаты поиска <em>"{{ query_string }}":</em></h2>
                    {% endif %}
                </div>
                <div class="products-group_wrapper">
                    {% include 'catalog/products-list.html' %}
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}

catalog/templates/catalog/sidebar.html
{% load static %}
{% load catalog_tags %}
<aside class="catalog__aside sidebar">
    <form class="sidebar_search" method="get" action="{% url 'catalog:products_by_cat' slug %}">
        {{ search_form.as_p }}
        <button type="submit">
            <img width="32" height="32" src="{% static 'img/icon-search.png' %}" alt="поиск">
        </button>
    </form>

    <form class="form-filters" method="post">
        {% csrf_token %}
        <input type="hidden" name="page" value="1">
        {% if prices.max > 2000 %}
        <div class="sidebar_prices">
            <input type="text" class="js-range-slider" name="price" value=""
            data-min="{{ prices.min | floatformat:'0' | min_price }}"
            data-max="{{ prices.max | floatformat:'0' | max_price }}"
            data-from="{{ prices.current_min }}"
            data-to="{{ prices.current_max }}"
            data-step="1000">
        </div>
        {% endif %}

        {% for filter in filters %}
        {% if filter.values %}
        <div class="sidebar-filters">
            <h3 class="sidebar-filters__header">{{ filter.name }}</h3>
            <ul class="sidebar-filters__items">
                {% for key in filter.values %}
                <li>
                    <input type="checkbox" id="f-{{ forloop.counter }}-{{ forloop.parentloop.counter }}" name="{{ filter.slug }}"
                           value="{{ key.value }}">
                    <span class="custom-checkbox"></span>
                    <label for="f-{{ forloop.counter }}-{{ forloop.parentloop.counter }}">{{ key.value }}</label>
                </li>
                {% endfor %}
            </ul>
        </div>
        {% endif %}
        {% endfor %}
        <button class="sidebar-filters__submit" type="submit" disabled>Применить</button>
    </form>
</aside>

catalog/templates/catalog/single.html
{% extends 'layout/base.html' %}
{% load thumbnail %}
{% load static %}

{% block title %}
    {{ product.name }}
{% endblock %}

{% block breadcrumbs %}
{% include 'breadcrumbs.html' %}
{% endblock %}

{% block content %}
    <main class="product">
        <div class="container">
            <h1 class="product__title">
                {{ product.name }}
            </h1>
            <p class="product__sku">
                Код: {% firstof product.sku '#Н/Д' %}
            </p>
            <div class="product__content">

                <div class="product__gallery gallery">
                    <div class="aside-gallery {% if product.images.count > 3 %}gallery{% else %}static{% endif %}">
                        {% for image in product.images.all %}
                            <div class="aside-gallery__item" data-slick-index="{{ forloop.counter0 }}">
                                {% if image.file %}
                                <img src="{{ image.file | thumbnail_url:'small' }}"
                                     alt="{{ image.alt }}" loading="lazy">
                                {% elif image.image_url %}
                                <img src="{{ image.image_url }}"
                                     alt="{{ image.alt }}" loading="lazy">
                                {% endif %}
                            </div>
                        {% endfor %}
                    </div>
                    <div class="main-product-gallery">
                        {% for image in product.images.all %}
                            <div class="main-product-gallery__item">
                                <div class="thumb">
                                    {% if image.file %}
                                    <img src="{{ image.file | thumbnail_url:'medium' }}"
                                         alt="{{ image.alt }}" loading="lazy">
                                    {% elif image.image_url %}
                                    <img src="{{ image.image_url }}"
                                         alt="{{ image.alt }}" loading="lazy">
                                    {% endif %}
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                    {% include 'wishlist/add-to-wishlist-form.html' %}

                </div>
                <!-- /.product__gallery -->

                <div class="product__info">
                    <div class="product__price">
                        {% if product_type == 'variable' %}
                            от {{ min_price | floatformat:"0" }} руб.
                        {% else %}
                            {% if product.price == 1.00 %}
                                <p>Цена по запросу</p>
                            {% else %}
                                {% if product.price_sale %}
                                <del>
                                    {{ product.price | floatformat:"0" }} руб.
                                </del>
                                &nbsp;
                                <ins>
                                    {{ product.price_sale | floatformat:"0" }} руб.
                                </ins>
                                {% else %}
                                    <span>
                                        {{ product.price | floatformat:"0" }} руб.
                                    </span>
                                {% endif %}
                            {% endif %}
                        {% endif %}

                    </div>
                    {% if product_type != 'variable' %}
                        <form action="{% url 'cart:cart_add' product.id %}" method="post" class="add-to-cart-form">
                            {% csrf_token %}
                            <div class="product__quantity quantity">
                                <span>Выберите количество:</span>
                                <div class="quantity__group">
                                    <button type="button" class="decr">-</button>
                                    {% for field in cart_product_form %}
                                        {{ field }}
                                    {% endfor %}
                                    <button type="button" class="inc">+</button>
                                </div>
                            </div>
                            {% if product.excerpt %}
                            <div class="product__excerpt">
                                {{ product.excerpt }}
                            </div>
                        {% endif %}
                        <ul class="product__features product-features">
                            <li class="product-features__item">
                                <div class="thumb">
                                    <img src="{% static 'img/icon-delivery-secondary.png' %}" alt="доставка">
                                </div>
                                Доставка по Москве за 2-3 дня <br>
                                Доставка по всей России
                            </li>
                        </ul>
                        <div class="product__add-to-cart">
                            <button type="submit" class="btn btn_add-to-cart"><span>Купить</span></button>
                            <a href="{% url 'cart:cart_detail' %}" class="cart-link">
                                <img src="{% static 'img/icon-cart-dark.png' %}" alt="корзина">
                                <span>Корзина</span>
                            </a>
                        </div>

                        </form>
                    {% else %}
                        {% if product.excerpt %}
                            <div class="product__excerpt">
                                {{ product.excerpt }}
                            </div>
                        {% endif %}
                        <ul class="product__features product-features">
                            <li class="product-features__item">
                                <div class="thumb">
                                    <img src="{% static 'img/icon-delivery-secondary.png' %}" alt="доставка">
                                </div>
                                Доставка по Москве за 2-3 дня <br>
                                Доставка по всей России
                            </li>
                        </ul>
                        <div class="variation-goto-wrapper">
                            <button type="button" class="btn btn_goto-vars"><span>Выбрать товар</span></button>
                        </div>
                    {% endif %}

                </div>
                <!-- /.product__info -->

            </div>
            <!-- /.product__content -->
            {% if product_type == 'variable' %}
                {% include 'catalog/variable-tabs.html' %}
            {% endif %}
            <div class="product__tabs product-tabs">
                <div class="product-tabs__group tabs-header">
                    {% if product.description %}
                        <button type="button" class="tabs-header__item" data-id="tab-1">Описание</button>
                    {% endif %}
                    {% if product_attributes %}
                        <button type="button" class="tabs-header__item" data-id="tab-2">Характеристики</button>
                    {% endif %}
                    {% if delivery %}
                        {% if delivery.content.html %}
                        <button type="button" class="tabs-header__item" data-id="tab-3">Оплата и доставка</button>
                        {% endif %}
                    {% endif %}
                    <button type="button" class="tabs-header__item" data-id="tab-4">Отзывы
                        (<span class="reviews-cnt">{{ product.reviews.all|length }}</span>)
                    </button>
                    <button type="button" class="tabs-header__item" data-id="tab-5">Задать вопрос</button>
                </div>
                <div class="tabs-content">
                    {% if product.description %}
                        <div class="tabs-content__item" id="tab-1">
                            <div class="page-content">
                            {{ product.description.html | safe }}
                            </div>
                        </div>
                    {% endif %}
                    {% if product_attributes  %}
                        <div class="tabs-content__item" id="tab-2">
                            <ul class="attributes-list">
                            {% for attribute in product_attributes %}
                                <li class="attributes-list__item attribute-item">
                                    <em class="attribute-item__label">
                                        {{ attribute.name }}
                                    </em>
                                    <strong class="attribute-item__value">
                                        {{ attribute.value }}
                                    </strong>
                                </li>
                            {% endfor %}
                            </ul>
                        </div>
                    {% endif %}
                    {% if delivery %}
                    <div class="tabs-content__item" id="tab-3">
                        <div class="page-content">
                            {{ delivery.content.html | safe }}
                        </div>
                    </div>
                    {% endif %}
                    <div class="tabs-content__item" id="tab-4">
                        <form class="form-product-review" action="." method="post">
                            {% csrf_token %}
                            {{ review_form.as_p }}
                            <button type="submit" class="btn_submit-review">Отправить</button>
                        </form>
                        <ul class="reviews-list">
                            {% for review in product.reviews.all %}
                                {% include 'reviews/review-detail.html' %}
                            {% endfor %}
                        </ul>

                    </div>

                    <div class="tabs-content__item" id="tab-5">
                        <form class="form-question" action="{% url 'catalog:question' %}" method="post">
                            {% csrf_token %}
                            <input type="hidden" name="product" value="{{ product.name }}">
                            <input type="text" name="name" placeholder="Имя" required>
                            <input type="tel" name="tel" placeholder="Телефон" required>
                            <textarea name="msg" cols="30" rows="10" placeholder="Вопрос" required></textarea>
                            <button type="submit" class="btn_submit-review">Отправить</button>
                            <div class="notice"></div>
                        </form>

                    </div>

                </div>
            </div>
            <!-- /.product-tabs -->

        </div>
    </main>
    <!-- /.product -->

    {% if similar_products|length %}
    <section class="top-products">
        <div class="container">
            <div class="section-header">
                <h2 class="section-header__title">Похожие товары</h2>
            </div>
            <ul class="top-products__slider products-slider">
                {% for product in similar_products %}
                    {% include 'catalog/archive-product.html' %}
                {% endfor %}
            </ul>
        </div>
    </section>
    {% endif %}

    {% if accessories|length %}
    <section class="latest-products">
        <div class="container">
            <div class="section-header">
                <h2 class="section-header__title">Аксесуары</h2>
            </div>
            <ul class="latest-products__slider products-slider">
                {% for product in accessories %}
                    {% include 'catalog/archive-product.html' %}
                {% endfor %}
            </ul>
        </div>
    </section>
    {% endif %}
{% endblock %}


{% block scripts %}
<script src="{% static 'js/variation.js' %}"></script>
{% endblock %}